### ISSUE TITLE
Recognizer crashes both when importing grammar from JSGF and dynamically generating grammar

### ISSUE THREAD

**Issue by devanhurst** [watsonbox/pocketsphinx-ruby#25]
```
configuration = Pocketsphinx::Configuration::Grammar.new do
  sentence "test"
end

recognizer = Pocketsphinx::LiveSpeechRecognizer.new(configuration)

recognizer.recognize do
  puts speech.to_s
end
```
## 

_RESULT_

```
/Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:10:in `block in api_call': Decoder#unset_search failed with error code -1 (Pocketsphinx::API::Error)
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:8:in `tap'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:8:in `api_call'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:178:in `unset_search'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/configuration/grammar.rb:15:in `post_init_decoder'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:206:in `post_init_decoder'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:194:in `init_decoder'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:30:in `initialize'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:22:in `new'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:22:in `decoder'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:86:in `stop'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:59:in `ensure in recognize'
from /Users/devanhurst/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:59:in `recognize'
from defuser.rb:13:in `<main>'
```

**Comment by devanhurst** [comment]
SOLVED:

After installing the gem, this line remained included, even though it was removed in a commit. I don't understand why this happened.

    decoder.unset_search

https://github.com/watsonbox/pocketsphinx-ruby/commit/6c0446ddb10b3106ed7a29136cd4c0b1c49f68d6
