### ISSUE TITLE
Could not open library 'libsphinxbase.so'

### ISSUE THREAD

**Issue by codegeek319** [watsonbox/pocketsphinx-ruby#29]
Hey i just did what you did and there is an error it showing i have tried many things but still the error remains

/home/abdul/.rvm/gems/ruby-2.4.1/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsphinxbase': libsphinxbase: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libsphinxbase.so': libsphinxbase.so: cannot open shared object file: No such file or directory
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx/api/sphinxbase.rb:5:in `<module:Sphinxbase>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx/api/sphinxbase.rb:3:in `<module:API>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx/api/sphinxbase.rb:2:in `<module:Pocketsphinx>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx/api/sphinxbase.rb:1:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx.rb:6:in `require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx.rb:6:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx-ruby.rb:1:in `require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/pocketsphinx-ruby-0.4.0/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:83:in `require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:83:in `block (2 levels) in require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:78:in `each'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:78:in `block in require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:67:in `each'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:67:in `require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler.rb:114:in `require'
	from /home/abdul/projects/lyrics/config/application.rb:7:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/abdul/projects/lyrics/bin/rails:9:in `require'
	from /home/abdul/projects/lyrics/bin/rails:9:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/abdul/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/abdul/projects/lyrics/bin/spring:15:in `require'
	from /home/abdul/projects/lyrics/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by RishabhTayal** [comment]
I am getting the same error. Any solution for this?

**Comment by ErwanDelhoveUCL** [comment]
There is a chance that the installation via the command `brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase` didn't work. So you have to try it again and see if everything worked fine. There is a chance that you encountered issue similar to this [one](https://github.com/watsonbox/homebrew-cmu-sphinx/issues/8).
