### ISSUE TITLE
Segfault when reconfiguring

### ISSUE THREAD

**Issue by chendo** [watsonbox/pocketsphinx-ruby#4]
When running the live speech recognizer example, I get a segfault when it reconfigures.

```
You said 'hello computer'. Keyword is now 'goodbye computer'
ERROR: "acmod.c", line 1110: Frame -4 outside queue of 0 frames, 12 alloc (4 > 12), cannot score
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/call_helpers.rb:8: [BUG] Segmentation fault at 0x00000000000004
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0014 p:---- s:0050 e:000049 CFUNC  :ps_end_utt
c:0013 p:0031 s:0046 e:000045 METHOD /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/call_helpers.rb:8
c:0012 p:0012 s:0040 e:000039 METHOD /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/decoder.rb:91
c:0011 p:0028 s:0037 e:000036 BLOCK  /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:113 [FINISH]
c:0010 p:---- s:0034 e:000033 CFUNC  :tap
c:0009 p:0013 s:0031 e:000030 METHOD /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:109
c:0008 p:0023 s:0026 e:000025 BLOCK  /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:55 [FINISH]
c:0007 p:---- s:0024 e:000023 CFUNC  :loop
c:0006 p:0007 s:0021 e:000020 BLOCK  /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:54 [FINISH]
c:0005 p:---- s:0018 e:000017 CFUNC  :initialize
c:0004 p:---- s:0016 e:000015 CFUNC  :new
c:0003 p:0071 s:0011 e:000010 METHOD /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:53
c:0002 p:0067 s:0006 E:0022d8 EVAL   -:9 [FINISH]
c:0001 p:0000 s:0002 E:001a78 TOP    [FINISH]

-:9:in `<main>'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:53:in `recognize'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:53:in `new'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:53:in `initialize'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:54:in `block in recognize'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:54:in `loop'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:55:in `block (2 levels) in recognize'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:109:in `recognize_continuous'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:109:in `tap'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb:113:in `block in recognize_continuous'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/decoder.rb:91:in `end_utterance'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/call_helpers.rb:8:in `api_call'
/Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/call_helpers.rb:8:in `ps_end_utt'

-- C level backtrace information -------------------------------------------
0   ruby                                0x00000001009800f0 rb_vm_bugreport + 144
1   ruby                                0x0000000100833ba1 report_bug + 305
2   ruby                                0x0000000100833a64 rb_bug + 180
3   ruby                                0x00000001009024bc sigsegv + 156
4   libsystem_platform.dylib            0x00007fff89505f1a _sigtramp + 26
5   libpocketsphinx.dylib               0x00000001011e48ba hmm_vit_eval + 525
6   ???                                 0x0000000000000000 0x0 + 0

-- Other runtime information -----------------------------------------------

* Loaded script: -

* Loaded features:

    0 enumerator.so
    1 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/encdb.bundle
    2 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/trans/transdb.bundle
    3 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/rbconfig.rb
    4 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/compatibility.rb
    5 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/defaults.rb
    6 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/deprecate.rb
    7 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/errors.rb
    8 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/version.rb
    9 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/requirement.rb
   10 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/platform.rb
   11 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/basic_specification.rb
   12 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/stub_specification.rb
   13 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/util/stringio.rb
   14 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb
   15 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/exceptions.rb
   16 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   17 thread.rb
   18 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/thread.bundle
   19 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb
   20 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   21 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems.rb
   22 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/path_support.rb
   23 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb
   24 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/pathname.bundle
   25 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/pathname.rb
   26 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/constants.rb
   27 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/io/console.bundle
   28 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/user_interaction.rb
   29 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/etc.bundle
   30 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/config_file.rb
   31 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb
   32 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/current_ruby.rb
   33 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/shared_helpers.rb
   34 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb
   35 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/gem_path_manipulation.rb
   36 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/gem_helpers.rb
   37 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/match_platform.rb
   38 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/rubygems_ext.rb
   39 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/version.rb
   40 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler.rb
   41 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/settings.rb
   42 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/digest.bundle
   43 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/digest.rb
   44 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/digest/sha1.bundle
   45 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/set.rb
   46 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/definition.rb
   47 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/dependency.rb
   48 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/ruby_dsl.rb
   49 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/dsl.rb
   50 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/source_list.rb
   51 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/source.rb
   52 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb
   53 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/generic.rb
   54 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/ftp.rb
   55 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/http.rb
   56 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/https.rb
   57 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/ldap.rb
   58 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/ldaps.rb
   59 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/mailto.rb
   60 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/uri.rb
   61 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/socket.bundle
   62 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/socket.rb
   63 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb
   64 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/protocol.rb
   65 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/zlib.bundle
   66 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/stringio.bundle
   67 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/exceptions.rb
   68 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/header.rb
   69 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/generic_request.rb
   70 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/request.rb
   71 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/requests.rb
   72 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb
   73 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/responses.rb
   74 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/proxy_delta.rb
   75 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/backward.rb
   76 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb
   77 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/date_core.bundle
   78 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/date/format.rb
   79 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/date.rb
   80 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/time.rb
   81 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/request.rb
   82 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/cgi/core.rb
   83 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/cgi/util.rb
   84 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/cgi/cookie.rb
   85 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/cgi.rb
   86 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/uri_formatter.rb
   87 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/fcntl.bundle
   88 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/openssl.bundle
   89 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/bn.rb
   90 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/cipher.rb
   91 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/config.rb
   92 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/digest.rb
   93 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/x509.rb
   94 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/buffering.rb
   95 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/ssl.rb
   96 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl.rb
   97 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/securerandom.rb
   98 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/resolv.rb
   99 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/remote_fetcher.rb
  100 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/text.rb
  101 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/name_tuple.rb
  102 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/spec_fetcher.rb
  103 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/source/rubygems.rb
  104 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/strscan.bundle
  105 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/source/path.rb
  106 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/source/git.rb
  107 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/lockfile_parser.rb
  108 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/lazy_specification.rb
  109 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb
  110 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/forwardable.rb
  111 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/spec_set.rb
  112 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/environment.rb
  113 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb
  114 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/index.rb
  115 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/remote_specification.rb
  116 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/endpoint_specification.rb
  117 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/dep_proxy.rb
  118 /Users/chendo/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/setup.rb
  119 /Users/chendo/.gem/ruby/2.1.5/extensions/x86_64-darwin-14/2.1.0-static/ffi-1.9.6/ffi_c.bundle
  120 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/platform.rb
  121 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/types.rb
  122 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/library.rb
  123 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/errno.rb
  124 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/pointer.rb
  125 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/memorypointer.rb
  126 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/struct_layout_builder.rb
  127 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/struct.rb
  128 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/union.rb
  129 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/managedstruct.rb
  130 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/callback.rb
  131 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/io.rb
  132 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/autopointer.rb
  133 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/variadic.rb
  134 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/enum.rb
  135 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi/ffi.rb
  136 /Users/chendo/.gem/ruby/2.1.5/gems/ffi-1.9.6/lib/ffi.rb
  137 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/version.rb
  138 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/sphinxbase.rb
  139 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/sphinxad.rb
  140 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/pocketsphinx.rb
  141 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/api/call_helpers.rb
  142 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/grammar/jsgf.rb
  143 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/grammar/jsgf_builder.rb
  144 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/configuration/setting_definition.rb
  145 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/configuration/base.rb
  146 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/configuration/default.rb
  147 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/configuration/keyword_spotting.rb
  148 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/configuration/grammar.rb
  149 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/audio_file.rb
  150 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/microphone.rb
  151 /Users/chendo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/delegate.rb
  152 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/decoder.rb
  153 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/speech_recognizer.rb
  154 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/live_speech_recognizer.rb
  155 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx/audio_file_speech_recognizer.rb
  156 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx.rb
  157 /Users/chendo/.gem/ruby/2.1.5/gems/pocketsphinx-ruby-0.1.1/lib/pocketsphinx-ruby.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html
```

**Comment by nshmyrev** [comment]
This is a bug in pocketsphinx caused by recent update, I'm looking on it.

**Comment by nshmyrev** [comment]
This issue has been just fixed in pocketsphinx. Please update pocketsphinx and try again.

**Comment by chendo** [comment]
Confirmed fixed. Had to update sphinxbase as well. Thanks!
